<template>
  <MoleculesBreadcrumbs pageName="Aviso legal" pageLink="legal-wraning" />
  <section class="max-w-screen-2xl mx-auto md:px-16 px-4 pt-10 pb-24">
    <h2 class="text-[28px] font-medium">Aviso legal</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">Al acceder este sitio y todas las páginas que lo conforma usted está de acuerdo con los términos y condiciones expuestas a continuación. Si usted no está de acuerdo con estos términos y condiciones no ingrese al sitio ni a ninguna de las páginas que lo conforman. La navegación por el sitio web de GUIA MUNDIAL HISPANA atribuye la condición de usuario del mismo e implica la aceptación plena y sin reservas de todas y cada una de las disposiciones incluidas en este Aviso Legal, que pueden sufrir modificaciones. El usuario se obliga a hacer un uso correcto del sitio web de conformidad con las leyes, la buena fe, el orden público, los usos del tráfico y el presente Aviso Legal. El usuario responderá frente a GUIA MUNDIAL HISPANA o frente a terceros, de cualesquiera daños y perjuicios que pudieran</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Limitación de la responsabilidad</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">Con toda la extensión permitida por la ley aplicable, Guía Mundial Hispana.com no asume responsabilidad contractual o extracción actual alguna de los daños y perjuicios directos, indirectos, incidentales, especiales o emergentes (incluso si Guía Mundial Hispana.com hubiera sido advertido de la posibilidad de los mismos) que traigan causa del: (i) uso o de la imposibilidad de usar el servicio; del coste incurrido para la obtención de bienes y servicios sustitutivos, o de cualesquiera bienes comprados u obtenidos o información o mensajes recibidos u operaciones concertadas en, a través o desde el servicio; del acceso no autorizado ó alteración de sus transmisiones de datos; declaraciones de conducta de terceros a través del servicio. El usuario acuerda además que Guía Mundial Hispana.com no será responsable de ningún daño o perjuicio derivado de la interrupción, suspensión o terminación del servicio, incluyendo, pero no limitándose, a daños, lucro cesante, uso, datos u otros bienes intangibles, o perjuicios directos, indirectos, incidentales, especiales, consecuentes, o ejemplares, ya sea que tal interrupción, suspensión o terminación sea justificada o no, negligente ó intencional, advertida ó inadvertida.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Negociaciones con anunciantes</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">El usuario acuerda que cualquier negociación o participación en promociones de anunciantes disponibles en el servicio, incluyendo el pago y la entrega de bienes y servicios, u otros términos, garantías o manifestaciones en relación con tales relaciones, se realizará exclusivamente entre usuario y respectivo anunciante. Guía Mundial Hispana.com no tendrá ninguna responsabilidad con relación al usuario o tercero, ya sea contractual, extracontractual u otra, o cualquier daño o perjuicio de cualquier tipo que se incurra como resultado de dichas relaciones o como consecuencia de la presencia de tales anunciantes en el servicio.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Indemnización</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">El usuario acuerda que cualquier negociación o participación en promociones de anunciantes disponibles en el servicio, incluyendo el pago y la entrega de bienes y servicios, u otros términos, garantías o manifestaciones en relación con tales relaciones, se realizará exclusivamente entre usuario y respectivo anunciante. Guía Mundial Hispana.com no tendrá ninguna responsabilidad con relación al usuario o tercero, ya sea contractual, extracontractual u otra, o cualquier daño o perjuicio de cualquier tipo que se incurra como resultado de dichas relaciones o como consecuencia de la presencia de tales anunciantes en el servicio.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Prohibición de revender el servicio</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">Usted se obliga a no reproducir, duplicar, copiar, vender, revender o explotar para fines comerciales, cualquier sección del servicio, uso o acceso al mismo.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Vínculos</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">Tanto el servicio como terceros podrán proporcionar vínculos a otros sitios o recursos de la red mundial. Debido a que Guía Mundial Hispana.com no tiene control alguno sobre dichos sitios o recursos, usted reconoce y acepta que Guía Mundial Hispana.com no será responsable por la disponibilidad de los sitios o recursos externos ni por cualquier contenido, publicidad, productos, servicios u otro tipo de material contenido ó a disposición en tales sitios o recursos. El usuario reconoce y acepta que Guía Mundial Hispana.com no será responsable, directa o indirectamente, por cualquier daño o perjuicio causado o que se presuma que sea causado por tales contenidos, productos o servicios disponibles en dichos sitios o recursos externos, o por la utilización o confianza depositada por el usuario en tales contenidos, productos o servicios.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Derechos de propiedad</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">Usted reconoce y acepta que el servicio y cualquier software usado en relación con el servicio ("Software") contienen información confidencial y de propiedad ajena protegida por la legislación de propiedad intelectual y otras disposiciones legales. Además usted reconoce y acepta que el contenido incluyendo, pero no limitándose, textos, programas, canciones, sonidos, fotografías, gráficos, videos u otros material contenidos en propagandas disponibles en el servicio, así como también informaciones divulgadas al usuario a través del servicio o de anunciantes, está protegido por derechos de autor, marcas comerciales, patentes y otros derechos de propiedad intelectual y legislación aplicable. El usuario reconoce y acuerda que solamente podrá utilizar tales materiales e informaciones según lo expresamente autorizado por Guía Mundial Hispana.com o por los anunciantes, y no podrá copiar, reproducir, transmitir, distribuir o crear obras derivadas a partir de tales materiales o informaciones sin la expresa autorización del respectivo propietario. Guía Mundial Hispana.com le otorga una licencia y derecho personal, intransferible y no exclusivo para utilizar el código objeto de su Software en un solo ordenador, siempre que Usted (y sin permitírselo a un tercero) no copie, modifique, cree un trabajo derivado de ello, invierta el proceso, invierta el montaje o de algún modo intente descubrir algún código de acceso, vender, ceder, sub licenciar, prestar garantía sobre o de algún modo transferir cualesquiera derecho en el Software. Usted se obliga a no modificar el Software de ninguna manera, o utilizar versiones de Software modificadas con el fin, entre otros, de obtener acceso no autorizado al Servicio. Usted se obliga a no acceder al Servicio por otros medios que no sean a través de la interface que Guía Mundial Hispana.com proporciona para acceder al Servicio.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Garantía limitada</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">A- El uso del servicio será bajo exclusivo riesgo y responsabilidad del usuario. El servicio es suministrado gratuitamente y depende de la funcionalidad de varios factores, como la interacción de servidores y servicios de telecomunicaciones de terceros, la adecuación de los equipos de usuario y destinatario del mensaje. Considerando tales factores, Guía Mundial Hispana.com empleará sus mejores esfuerzos para que los mensajes de e-mail enviados a través del servicio, sean recibidos por el destinatario correcto y sin interferencias. Sin embargo, por estas mismas
    razones, Guía Mundial Hispana.com no puede garantizar que los mensajes serán entregados al destinatario correcto, en un plazo adecuado, o no sufrirán extravío, divulgación o violación por partes de terceros no autorizados, como por ejemplos "hackers". Se aconseja al usuario no confiar exclusivamente en el servicio para enviar informaciones importantes o confidenciales y Guía Mundial Hispana.com no se responsabilizará por ninguna falla resultante del envío de mensajes por parte del usuario.
    <br />
    <br />
    B- Guía Mundial Hispana.com no ofrece garantías de cualquier naturaleza con relación al servicio, ya sean expresas o implícitas, incluyendo, pero no limitándose a las garantías implícitas de comercialización, idoneidad para un propósito particular.
    <br />
    <br />
    C- Guía Mundial Hispana.com no garantiza que el servicio cumplirá con los requisitos y/o necesidades del usuario, o que el servicio se prestará de manera ininterrumpida, segura o libre de error.
    <br />
    <br />
    D- Guía Mundial Hispana.com tampoco otorga ninguna garantía en cuanto a los resultados que se puedan obtener del uso del servicio o e  relación con la exactitud o confiabilidad de cualquier información obtenida a través del servicio, ni que los defectos en los programas serán corregidos.
    <br />
    <br />
    E- Guía Mundial Hispana.com no otorga ninguna garantía en relación con bienes o servicios comprados u obtenidos a través del servicio, o cualquier operación realizada a través del mismo.
    <br />
    <br />
    F- Ninguna asesoría o información, ya sea oral o por escrito obtenida por el usuario de Guía Mundial Hispana.com a través del servicio dará origen a ninguna garantía que no sea expresamente especificada en el presente acuerdo.
    <br />
    <br />
    G- El usuario reconoce y acuerda que cualquier material y/o información obtenida a través del servicio o de su utilización, estará sujeta a su entero criterio y riesgo; y que será el único responsable de cualquier daño ocurrido en su computadora o pérdida de datos que pueda resultar de recibir tal material.</p>
    <!--  -->
    <h2 class="text-[28px] font-medium">Conducta del usuario</h2>
    <hr class="mt-2 border-#F5F5F5 mb-14">
    <p class="mb-20 text-sm text-black">
      El usuario acepta que toda la información, datos, textos, software, música, sonido, fotografías, gráficos, vídeos, mensajes u otro material, ya sea públicamente enviado, u objeto de transmisiones personales ("Contenido"), serán de la exclusiva responsabilidad de la persona donde dicho Contenido se haya originado. Esto significa que el usuario, y no Guía Mundial Hispana.com, es plenamente responsable de todo el Contenido que ponga a disposición de los demás, exhiba, envíe por e-mail o de cualquier manera transmita. Guía Mundial Hispana.com no ejerce control sobre el
      Contenido enviado a través del Servicio y, así, no puede garantizar la precisión, integridad o calidad de dicho Contenido. El usuario entiende que,  al utilizar el Servicio, es susceptible de visualizar Contenidos que puedan considerarse ofensivos, indecentes o inaceptables. Guía Mundial Hispana.com no asumirá responsabilidad alguna, bajo ninguna circunstancia, por el Contenido, incluyendo, sin limitación, errores u omisiones en el Contenido, daños o perjuicios derivados del uso del Contenido exhibido, enviado por e-mail o, de cualquier modo, transmitido a través del
      Servicio. El usuario se obliga a no utilizar el Servicio con el fin de:
      <br />
      <br />
      a. Poner a disposición de los demás, enviar por e-mail o, de cualquier modo, transmitir Contenidos ilegales, dañinos, molestos, amenazadores, abusivos, tortuosos, difamatorios, vulgares, obscenos, invasores de la intimidad de terceros, odiosos, xenófobos, racistas o, de algún modo, inaceptables; b. Perjudicar a menores, de manera alguna; c. Hacerse pasar o fingir ser cualquier otra persona o entidad, incluyendo, sin limitación, un representante de Guía Mundial Hispana.com, fundador, guía o anfitrión de fórums, o de cualquier otro modo mentir o fingir sobre su relación con cualquier otra persona o afiliación a cualquier entidad; d. Falsificar rúbricas o, de otro modo manipular identificativos con el fin de disfrazar la naturaleza del Contenido transmitido a través del Servicio; e. Poner a disposición de los demás usuarios, enviar por e-mail o, de algún modo transmitir, cualquier Contenido que, de acuerdo con las disposiciones aplicables o relaciones contractuales existentes, Usted no está autorizado a transmitir (tales como información privilegiada, información protegida por derechos de propiedad industrial o intelectual o información sobre la cual tiene un deber de confidencialidad). f. Poner a disposición de los demás usuarios, enviar por e-mail o, de algún modo, transmitir Contenido alguno susceptible de infringir patentes, marcas, secretos comerciales, derechos de autor   u otros derechos de terceros ("Derechos"); g. Poner a disposición de los demás usuarios, enviar por e-mail o, de algún modo, transmitir publicidad no solicitada o autorizada, material publicitario, "correo basura", "cartas en cadena", "estructuras piramidales", o cualquier otra forma de solicitud, excepto en aquellas áreas (tales como espacios comerciales) que hayan sido exclusivamente concebidos para ello; h. Poner a disposición de los demás usuarios, enviar por e-mail o, de algún modo, transmitir material alguno que sea portador de virus o cualquier otro código informático, archivos o programas diseñados para interrumpir, destruir o limitar el funcionamiento de cualquier software, hardware o equipo de telecomunicaciones; i. Interrumpir el curso normal de las conversaciones, provocar que la pantalla del ordenador adquiera mayor velocidad de la normal con la que los usuarios pueden participar en el Servicio, o de algún modo actuar de manera que afecte de forma negativa a la posibilidad de comunicarse en tiempo real; j. Interferir o interrumpir el Servicio, servidores o redes conectados al Servicio, o incumplir los requisitos, procedimientos y regulaciones de la política de redes conectadas al Servicio; k. Violar con/sin intención cualquier ley aplicable, ya sea local, de las Comunidades Autónomas, nacional o internacional, incluidas, sin limitación, las disposiciones reguladoras de los mercados de valores. l. "Acechar" o de algún modo hostigar a terceros; o l. Recoger o almacenar información personal sobre otros usuarios.
      <br />
      <br />
      El usuario reconoce y acepta que Guía Mundial Hispana.com no examina los Contenidos con anterioridad a su puesta en disposición o transmisión, pero éste y sus representantes estarán facultados (pero no obligados) a rechazar o desplazar cualquier Contenido que esté disponible en el Servicio. Sin perjuicio de lo anterior, Guía Mundial Hispana.com y sus representantes estarán plenamente facultados para suprimir cualquier Contenido que vulnere las Condiciones o que de algún modo sea inaceptable. Usted se obliga a evaluar los Contenidos y asume todos los riesgos
      derivados de los mismos o del uso de cualquier Contenido, incluyendo la fiabilidad, utilidad y la finalidad de tal Contenido. A estos efectos, Usted reconoce y acepta que Guía Mundial Hispana.com no está garantizando la fiabilidad de cualquier Contenido creado o disponible en Guía Mundial Hispana.com.
      <br />
      <br />
      El usuario reconoce y acepta que Guía Mundial Hispana.com puede conservar o revelar el Contenido si es requerido para ello en virtud de las disposiciones legales aplicables o, de buena fe, lo considerara necesario para: (a) Dar cumplimiento a la ley o a procedimientos legales, tales como órdenes judiciales o de órganos administrativos competentes; (b) Hacer cumplir las presentes Condiciones; (c) Contestar reclamaciones relativas a violaciones de derechos de terceros; o (d) Proteger los legítimos intereses de Guía Mundial Hispana.com, sus usuarios y el público en
      general. Usted entiende y acepta que el proceso técnico y transmisión del Servicio, incluido su Contenido, puede implicar: (a) Transmisiones a través de diversas redes; y (b) Modificaciones o cambios realizados al objeto de compatibilizar el Contenido con las necesidades técnicas de conexión de redes o dispositivos.
    </p>
  </section>
</template>